param (
    [Parameter(Mandatory=$true)]
    [int]$Names = 10
    )
    
    $firstNames = @("Yossi", "Avi", "Eli", "Itai", "Moshe", "Omer", "Amit", "Yaakov", "Noam", "Eitan", "Alon", "Yair", "Tomer", "Ronen", "David", "Shlomi", "Ori", "Avraham", "Rami", "Yonatan", "Shai", "Barak", "Yaron", "Nir", "Gil", "Boaz", "Ziv", "Lior", "Amir", "Assaf", "Yossi", "Nadav", "Tal", "Dan", "Meir", "Elad", "Haim", "Ofir", "Yehuda", "Shaul", "Shimon", "Gadi", "Omri", "Reuven", "Arik", "Erez", "Tzachi", "Aviv", "Matan", "Yehonatan", "Shahar", "Sara", "Yael", "Michal", "Hila", "Shira", "Liat", "Dana", "Noa", "Rivka", "Leah", "Esther", "Tali", "Roni", "Eden", "Maya", "Nitzan", "Hadar", "Tamar", "Dafna", "Galit", "Sigal", "Yaara", "Vered", "Naomi", "Gili", "Einat", "Racheli", "Ilana", "Orly", "Ruth", "Merav", "Ronit", "Moran", "Adi", "Dikla", "Batya", "Shani", "Carmit", "Gal", "Talya", "Keren", "Noga", "Shelly", "Sarit", "Liraz", "Tzipi", "Meital", "Eliana", "Batya", "Yaara", "Alma", "Shlomit", "Orit", "Miri", "Rachel", "Yafit", "Shani", "Dorit", "Or", "Ella", "Rina", "Tzvia", "Shira", "Bar", "Natalie", "Karen", "Jessica", "Emily", "Sarah", "Hannah", "Rachel", "Sophia", "Emma", "Olivia", "Lily", "Chloe", "Amelia", "Isabella", "Grace", "Mia", "Ella", "Charlotte", "Abigail", "Layla", "Ava", "Harper", "Leah", "Madison", "Scarlett", "Luna", "Zoe", "Ruby", "Hazel", "Aurora", "Alice", "Evelyn", "Sophie", "Eli", "Isaac", "Jacob", "Samuel", "Benjamin", "Michael", "Daniel", "David", "Joseph", "Aaron", "Noah", "Joshua", "Gabriel", "Zachary", "Levi", "Elijah", "Nathan", "Jonah", "Reuben", "Isaiah", "Adam", "Caleb", "Ethan", "Lucas", "Asher", "James", "Evan", "Matthew", "Jonathan", "Simon", "Alexander", "Oren", "Benny", "Elior", "Yoav", "Matan", "Shai", "Aharon", "Doron", "Baruch", "Avner", "Zohar", "Rafi", "Eliana", "Tova", "Bracha")
    $lastNames = @("Cohen", "Levi", "Mizrahi", "Peretz", "Biton", "Elbaz", "Shalom", "Gabay", "Avraham", "Ben-David", "Ben-Ari", "Almog", "Barak", "Shimon", "David", "Yosef", "Katz", "Dahan", "Amar", "Levy", "Sasson", "Malka", "Meir", "Zohar", "Ben-Shimon", "Aharon", "Rosenberg", "Hazan", "Nahmias", "Ben-Ezra", "Sharabi", "Ariel", "Ashkenazi", "Eldar", "Rubin", "Yaron", "Avital", "Ben-Tzion", "Golan", "Sapir", "Tamir", "Nimrodi", "Sivan", "Zamir", "Bar-On", "Rosen", "Azoulay", "Shani", "Shahar", "Ron", "Tal", "Halevy", "Oren", "Avneri", "Oron", "Harel", "Moyal", "Tzur", "Elad", "Sela", "Dayan", "Talmi", "Kaplan", "Ben-Zvi", "Margalit", "Turgeman", "Mor", "Goren", "Arad", "Barzilay", "Stern", "Ronen", "Gal", "Bar", "Neuman", "Shechter", "Ben-Haim", "Abadi", "Fridman", "Koren", "Peleg", "Shaked", "Zucker", "Orbach", "Goldstein", "Stein", "Bar-Lev", "Shemesh", "Segev", "Yehuda", "Danon", "Rosenthal", "Ziv", "Navon", "Shilo", "Perry", "Segal", "Tobi", "Elron", "Gigi", "Carmon", "Hasson", "Tzadok", "Alon", "Ben-Yehuda", "Giat", "Shlomo", "Romano", "Shein", "Shoval", "Vaknin", "Ben-Barak", "Samson", "Sharon", "Berger", "Elkayam", "Ben-Sasson", "Weinberg", "Adler", "Baruch", "Abraham", "Gazit", "Weiss", "Ben-Yosef", "Livne", "Harel", "Solomon", "Garfinkel", "Efron", "Mandel", "Roth", "Bernstein", "Silverman", "Schwartz", "Goldman", "Eisenberg", "Friedman", "Miller", "Rosenfeld", "Weinstein", "Wolf", "Abramson", "Klein", "Greenberg", "Steiner", "Levin", "Fuchs", "Isaacs", "Blumenthal", "Rosen", "Altman", "Feldman", "Gordon", "Schneider", "Leibowitz", "Richter", "Braun", "Cohen", "Levi", "Berman", "Hirsch", "Rosenzweig", "Steinberg", "Buchwald", "Gold", "Silver", "Kaufman", "Goldfarb", "Reich", "Horowitz", "Lang", "Goldschmidt", "Liebman", "Bloom", "Rabinowitz", "Freeman", "Landsman", "Spiegel", "Moss", "Pomerantz", "Reiss", "Tenenbaum", "Winter", "Sobel", "Markovitz", "Eisen", "Gershon", "Nussbaum", "Pasternak", "Weissman", "Hecht", "Zilberman", "Rothstein", "Schuster", "Schwartzman", "Vogel", "Katzman")

    for ($i = 1; $i -le $Names; $i++) {
        $ChosenFname = $firstNames | Get-Random
        $ChosenLname = $lastNames | Get-Random
        & .\AddUserToAD.ps1 -FName $ChosenFname -LName $ChosenLname
    }